### PR TITLE
Use Go Gopher for Go icon

### PR DESCRIPTION
**Pull request by itspage**

### CODE REVIEW

**Comment by EmmanuelBeziat** [comment]
Hi, thanks for the suggestion

I fear that the icon have too much details for this size. All of the icon set have 1, maximum 2 colors; this one doesn’t really match.

But I’ll try to find a gopher that match :)

**Comment by seraku24** [comment]
@EmmanuelBeziat Here's a [github](https://github.com/golang-samples/gopher-vector) with some vector art for golang's "gopher".  In particular, there's one that has no line work, just solid colors, which seems to fit in with the style of your icon pack better:

gopher-front

Apart from black and white, it has two shades of blue and a tan color.  Again, the detail is pretty fine, so it might not scale well as is.  But maybe you can work your magic on it.  `(:`

**Comment by EmmanuelBeziat** [comment]
It will be perfect, thanks! I'll merge your pull request and then work on one of the svg icons to get a nice and clean Gopher.

Thanks again!

**Comment by seraku24** [comment]
Just for the record, @itspage submitted this PR.  I was just passing by and saw that you were looking for additional reference work.  Don't want to be getting credit for someone else's work here.  `(:`

**Comment by EmmanuelBeziat** [comment]
It's now added in the new 1.1.54 version :) Thanks again

**Pull request merged**
