### PR TITLE
fixes #97 - Jenkinsfile

### LINKED ISSUE #97: Jenkinsfile icon request
## Icon request for Jenkinsfile

* [Jenkinsfile](https://jenkins.io/doc/book/pipeline/jenkinsfile/)
* Official icon (https://jenkins.io/sites/default/files/jenkins_favicon.ico or https://ih1.redbubble.net/image.453956192.1706/flat,750x1000,075,t.jpg)
* ~~Files extensions: *.ext1, *.ext2~~ n/a
* Specific files names: Jenkinsfile

Thanks!

### PR DESCRIPTION
**Pull request by Stoward94**
I hope you don't mind my creating a PR for the issue #97 that I raised.

### CODE REVIEW

**Comment by EmmanuelBeziat** [comment]
Hi,
I was hoping to find an icon that would suit better the "look & feel" of the other ones, but this is a tricky one…
I'll accept and merge your PR, if I find a better one someday I'll replace it.

Thanks!

**Comment by Stoward94** [comment]
That's fair enough, it does feel a little archaic but then so is Jenkins haha. Appreciated.

**Comment by EmmanuelBeziat** [comment]
It's done, check out the new version of the plugin ;)

**Comment by Stoward94** [comment]
@EmmanuelBeziat I just spotted a problem with this... it seems the file names string is case sensitive [line 835](https://github.com/Stoward94/vscode-great-icons/blob/5a4f1563718f8641581dd2c5ea4414d25c1b777e/icons.json#L835). Although the actual file is "Jenkinsfile" the declaration in the icons.json should be lowercase.

**Pull request merged**
